<a href="https://colab.research.google.com/github/HEON-WOOK/Machine-Learning/blob/main/%EB%9E%9C%EB%8D%A4%ED%8F%AC%EB%A0%88%EC%8A%A4%ED%8A%B8_%2C_%EC%84%A0%ED%98%95%ED%9A%8C%EA%B7%80%2C_%EB%8B%A4%ED%95%AD%ED%9A%8C%EA%B7%80_%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
perch_length = np.array([8.4, 13.7, 15.0, 16.2, 17.4, 18.0, 18.7, 19.0, 19.6, 20.0, 21.0,
       21.0, 21.0, 21.3, 22.0, 22.0, 22.0, 22.0, 22.0, 22.5, 22.5, 22.7,
       23.0, 23.5, 24.0, 24.0, 24.6, 25.0, 25.6, 26.5, 27.3, 27.5, 27.5,
       27.5, 28.0, 28.7, 30.0, 32.8, 34.5, 35.0, 36.5, 36.0, 37.0, 37.0,
       39.0, 39.0, 39.0, 40.0, 40.0, 40.0, 40.0, 42.0, 43.0, 43.0, 43.5,
       44.0])
perch_weight = np.array([5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 110.0,
       115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 130.0,
       150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 197.0,
       218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 514.0,
       556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 820.0,
       850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 1000.0,
       1000.0])

In [ ]:
from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target = train_test_split(perch_length,perch_weight,random_state=42) 

In [ ]:
train_input

array([19.6, 22. , 18.7, 17.4, 36. , 25. , 40. , 39. , 43. , 22. , 20. ,
       22. , 24. , 27.5, 43. , 40. , 24. , 21. , 27.5, 40. , 32.8, 26.5,
       36.5, 13.7, 22.7, 15. , 37. , 35. , 28.7, 23.5, 39. , 21. , 23. ,
       22. , 44. , 22.5, 19. , 37. , 22. , 25.6, 42. , 34.5])

In [ ]:
train_input = train_input.reshape(-1,1)
train_target = train_target.reshape(-1,1)

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(train_input,train_target)
lr.score(train_input,train_target)

0.9398463339976039

In [ ]:
test_input = test_input.reshape(-1,1)
test_target = test_target.reshape(-1,1)

lr.score(test_input,test_target)

0.8247503123313558

In [ ]:
import pandas as pd

In [ ]:
df =  pd.read_csv("https://bit.ly/perch_csv")
perch_full =df.to_numpy()
perch_full

array([[ 8.4 ,  2.11,  1.41],
       [13.7 ,  3.53,  2.  ],
       [15.  ,  3.82,  2.43],
       [16.2 ,  4.59,  2.63],
       [17.4 ,  4.59,  2.94],
       [18.  ,  5.22,  3.32],
       [18.7 ,  5.2 ,  3.12],
       [19.  ,  5.64,  3.05],
       [19.6 ,  5.14,  3.04],
       [20.  ,  5.08,  2.77],
       [21.  ,  5.69,  3.56],
       [21.  ,  5.92,  3.31],
       [21.  ,  5.69,  3.67],
       [21.3 ,  6.38,  3.53],
       [22.  ,  6.11,  3.41],
       [22.  ,  5.64,  3.52],
       [22.  ,  6.11,  3.52],
       [22.  ,  5.88,  3.52],
       [22.  ,  5.52,  4.  ],
       [22.5 ,  5.86,  3.62],
       [22.5 ,  6.79,  3.62],
       [22.7 ,  5.95,  3.63],
       [23.  ,  5.22,  3.63],
       [23.5 ,  6.28,  3.72],
       [24.  ,  7.29,  3.72],
       [24.  ,  6.38,  3.82],
       [24.6 ,  6.73,  4.17],
       [25.  ,  6.44,  3.68],
       [25.6 ,  6.56,  4.24],
       [26.5 ,  7.17,  4.14],
       [27.3 ,  8.32,  5.14],
       [27.5 ,  7.17,  4.34],
       [27.5 ,  7.05,  4.34],
       [27

In [ ]:
import numpy as np
perch_weight = np.array([5.9, 32.0, 40.0, 51.5, 70.0, 100.0, 78.0, 80.0, 85.0, 85.0, 110.0,
       115.0, 125.0, 130.0, 120.0, 120.0, 130.0, 135.0, 110.0, 130.0,
       150.0, 145.0, 150.0, 170.0, 225.0, 145.0, 188.0, 180.0, 197.0,
       218.0, 300.0, 260.0, 265.0, 250.0, 250.0, 300.0, 320.0, 514.0,
       556.0, 840.0, 685.0, 700.0, 700.0, 690.0, 900.0, 650.0, 820.0,
       850.0, 900.0, 1015.0, 820.0, 1100.0, 1000.0, 1100.0, 1000.0,
       1000.0])

In [ ]:
from sklearn.model_selection import train_test_split

train_input,test_input,train_target, test_target = train_test_split(perch_full,perch_weight,random_state=42)

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(include_bias = False)
poly.fit(train_input)
poly_train = poly.transform(train_input)
poly_test = poly.transform(test_input)


In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(poly_train, train_target)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
lr.score(poly_train, train_target)

0.9903183436982124

In [ ]:
lr.score(poly_test, test_target)

0.9714559911594132

In [ ]:
lr.predict((poly_test))

array([  29.31340356,   37.06927364,  251.83284456,  114.16483881,
        130.19864962,  780.17335409,  304.80129313,  178.36971814,
        911.24229748,  101.88050671, 1174.97238267,   38.31371268,
        287.9800756 ,  276.64644375])

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
wine = pd.read_csv ('https://bit.ly/wine-date')

In [ ]:
wine.columns

Index(['alcohol', 'sugar', 'pH', 'class'], dtype='object')

In [ ]:
data = wine[['alcohol', 'sugar', 'pH']].to_numpy()
target = wine['class'].to_numpy()

In [ ]:
train_input, test_input, train_target, test_target = train_test_split(data,target, random_state = 42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_validate

In [ ]:
rf = RandomForestClassifier(n_jobs = -1)

In [ ]:
scores = cross_validate(rf,train_input,train_target,return_train_score = True,n_jobs=-1 )

In [ ]:
scores

{'fit_time': array([0.58505177, 0.58913183, 0.57851648, 0.57273054, 0.33990502]),
 'score_time': array([0.10288382, 0.10341692, 0.10445142, 0.1030941 , 0.1022923 ]),
 'test_score': array([0.88102564, 0.8974359 , 0.90246407, 0.88911704, 0.88501027]),
 'train_score': array([0.99743392, 0.99692071, 0.99846075, 0.99820421, 0.99820421])}

In [ ]:
np.mean(scores['train_score'])

0.997844759088341

In [ ]:
np.mean(scores['test_score'])

0.8910105828463118

In [ ]:
rf.fit(train_input,train_target)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [ ]:
rf.predict((test_input))

array([1., 0., 1., ..., 1., 1., 1.])

In [ ]:
rf.score(train_input,train_target)

0.9973316912972086

In [ ]:
rf.score(test_input,test_target)

0.8824615384615384